# General settings
SERVER_MODE = 'Server'
CLIENT_MODE = 'Client'

# Ports
SERVER_BROADCAST_PORT = 1919
DEFAULT_SERVER_PORT = 9191


# Communications Codes
CODE_FIND_SERVER = 1
CODE_START_COMM = 2
CODE_CHALLENGE_START = 3
CODE_CHALLENGE_NOT_REQUIRED = 4
CODE_CHALLENGE_RESPONSE = 5
CODE_CHALLENGE_FAILED = 6
CODE_CHALLENGE_SUCCESS = 7
CODE_SAY_HELLO = 8
CODE_ACCEPT_NOTIFICATIONS = 9

# Server Settings
FIND_SERVER_TIMEOUT = 5  # 5 Seconds
SESSION_TIMEOUT = 5     # 20 Seconds
